export const CLIENT_STRINGS = {
  CREATE_SUCCESS: "Cliente cadastrado com sucesso!",
  CREATE_ERROR: "Um erro ocorreu ao tentar cadastrar o cliente!.",
  EDIT_SUCCESS: "Cliente editado com sucesso!",
  EDIT_ERROR: "Um erro ocorreu ao tentar editar o cliente!.",
  TIPO_LABEL: "Tipo",
  SELECT_TIPO: "Selecione o tipo",
  PF: "PF",
  PJ: "PJ",
  SUBMIT: "Cadastrar",
  SUBMIT_EDIT: "Editar",
  LOADING: "Loading...",
  CNPJ: "CNPJ",
  NOME_FANTASIA: "Nome Fantasia",
  RAZAO_SOCIAL: "Razão Social",
  NOME: "Nome",
  CPF: "CPF",
  CPF_HELP: "Este campo aceita apenas números",
  BACK: "Voltar",
  EMAIL: "Email",
  EMAIL_ERROR: "Este campo é obrigatório",
  DDD: "DDD",
  TELEPHONE: "Telefone",
  TELEPHONE_HELP: "DDD e Telefone aceita apenas números",
};
